apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-monitor
spec:
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
