apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rchat-api-deployment-monitor
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: rchat-api-deployment
  endpoints:
  - port: "4099"
