apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rchat-api-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rchat-api-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 4
        periodSeconds: 60
      - type: Percent
        value: 5
        periodSeconds: 60


          #  - type: Pods
          # pods:
          #     metric:
          #name: packets-per-second
          # target:
          # type: AverageValue
          #averageValue: 1k
          #  - type: Object
          # object:
          # metric:
          #  name: requests-per-second
          #  describedObject:
          #   apiVersion: networking.k8s.io/v1
          #      kind: Ingress
          #   name: main-route
          #   target:
          #   type: Value
          # value: 10k
