name: Docker Image CI

on:
  push:
    branches: [ "k8s" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3 
    - name: Build the docker image
      run: docker build . 
    
   
