name: Node.js CI

on:
  push:
    branches: [ "k8s" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    
    - name: docker build
    - run: docker build . 
    
   
